# Generated by Django 4.1.7 on 2023-03-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('change_project_users', 'Can add and remove users from project')]},
        ),
    ]
